#!/bin/sh

# Shell script wrapping the Forth cross compiler.

if test "$#" != 2; then
    echo "Usage: $0 <source.fth> <image.bin>"
    exit 1
fi

input="$PWD/$1"
output="$PWD/$2"

cd `dirname $0`/..
cp "$input" app.fth
echo include src/compiler.fth | forth
if test \! "$output" -ef image; then
    mv image "$output"
fi 
